version: '3.8'


services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.8
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'



  pyspark-notebook:
    image: quay.io/jupyter/pyspark-notebook
    hostname: jupyter
    environment:
         - GRANT_SUDO=yes
         - JUPYTER_ENABLE_LAB=yes
         - JUPYTER_TOKEN=SU2orange! 
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
  
  #ollama

volumes:
  notebooks:
  weaviate_data:


